version: '3.8'

services:
  zonaprop-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zonaprop-scraper
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
